RecipeWebsite/RecipeWebsite/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RecipeWebsite.Models;

namespace RecipeWebsite.Controllers
{
    public class LoginData
    {
        public string email { get; set; }
        public string password { get; set; }
    }
    public class LoginController : Controller
    {
        private readonly RecipeWebsiteDbContext _db;

        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;
        [BindProperty]
        public User User { get; set; }
        public LoginController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, RecipeWebsiteDbContext db)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            _db = db;
        }


        //public LoginController(RecipeWebsiteDbContext db)
        //{
        //    _db = db;
        //}

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index(string returnUrl)
        {
            User model = new User
            {
                ReturnUrl = returnUrl,
                ExternalLogins = (await signInManager.GetExternalAuthenticationSchemesAsync()).ToList()
            };

            return View(model);
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult ExternalLogin(string provider, string returnUrl)
        {
            var redirectUrl = Url.Action("ExternalLoginCallback", "Login",
                                new { ReturnUrl = returnUrl });
            var properties = signInManager
                .ConfigureExternalAuthenticationProperties(provider, redirectUrl);
            return new ChallengeResult(provider, properties);
        }

        [AllowAnonymous]
        public async Task<IActionResult> ExternalLoginCallback(string returnUrl = null, string remoteError = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");

            User loginViewModel = new User
            {
                ReturnUrl = returnUrl,
                ExternalLogins =
                        (await signInManager.GetExternalAuthenticationSchemesAsync()).ToList()
            };

            if (remoteError != null)
            {
                ModelState
                    .AddModelError(string.Empty, $"Error from external provider: {remoteError}");

                return View("Login", loginViewModel);
            }

            // Get the login information about the user from the external login provider
            var info = await signInManager.GetExternalLoginInfoAsync();
            if (info == null)
            {
                ModelState
                    .AddModelError(string.Empty, "Error loading external login information.");

                return View("Login", loginViewModel);
            }

            // If the user already has a login (i.e if there is a record in AspNetUserLogins
            // table) then sign-in the user with this external login provider
            var signInResult = await signInManager.ExternalLoginSignInAsync(info.LoginProvider,
                info.ProviderKey, isPersistent: false, bypassTwoFactor: true);

            if (signInResult.Succeeded)
            {
                return LocalRedirect(returnUrl);
            }
            // If there is no record in AspNetUserLogins table, the user may not have
            // a local account
            else
            {
                // Get the email claim value
                var email = info.Principal.FindFirstValue(ClaimTypes.Email);

                if (email != null)
                {
                    // Create a new user without password if we do not have a user already
                    var user = await userManager.FindByEmailAsync(email);

                    if (user == null)
                    {
                        user = new IdentityUser
                        {
                            UserName = info.Principal.FindFirstValue(ClaimTypes.Email),
                            Email = info.Principal.FindFirstValue(ClaimTypes.Email)
                        };

                        await userManager.CreateAsync(user);
                    }

                    // Add a login (i.e insert a row for the user in AspNetUserLogins table)
                    await userManager.AddLoginAsync(user, info);
                    await signInManager.SignInAsync(user, isPersistent: false);

                    return LocalRedirect(returnUrl);
                }

                // If we cannot find the user email we cannot continue
                ViewBag.ErrorTitle = $"Email claim not received from: {info.LoginProvider}";
                ViewBag.ErrorMessage = "Please contact support on Pragim@PragimTech.com";

                return View("Error");
            }
        }

        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
        }

        //public IActionResult Index()
        //{
        //    //User user = _db.Users.FirstOrDefault();
        //    return View();
        //}

        #region API Calls
        [HttpPost]
        public async Task<IActionResult> Index(LoginData logindata)
        {
            var userFromDb = await _db.Users.FirstOrDefaultAsync(u => u.Email == logindata.email && u.Password == logindata.password);
            if (userFromDb == null)
            {
                return Json(new { success = false, message = " Invalid email or password!" });
            }
            HttpContext.Session.SetString("Email", logindata.email);
            HttpContext.Session.SetInt32("UserId", userFromDb.Id);
            HttpContext.Session.SetString("Username", userFromDb.Username);
            return RedirectToAction("Index", "Home");
        }
        #endregion
    }
}

RecipeWebsite/RecipeWebsite/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RecipeWebsite.Models;
using System.IO;
using System.Web;
using Microsoft.AspNetCore.Http;

namespace RecipeWebsite.Controllers
{
    public class RegisterController : Controller
    {
        private readonly RecipeWebsiteDbContext _db;
        [BindProperty]
        public User User { get; set; }
        public RegisterController(RecipeWebsiteDbContext db)
        {
            _db = db;
        }

        public IActionResult Index(int? id)
        {
            //List<Pet> pets = new List<Pet>();
            //for{
            //    pets.Add()
            //}
            User = new User();
            if (id == null)
            {
                //create
                return View(User);
            }
            //update
            User = _db.Users.FirstOrDefault(u => u.Id == id);
            if (User == null)
            {
                return NotFound();
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index()
        {
            if (true || ModelState.IsValid)
            {
                if (User.Id == 0)
                {
                    if (User.ImageFile.Length > 0)
                    {
                        string filePath = AppDomain.CurrentDomain.BaseDirectory.Substring(0, AppDomain.CurrentDomain.BaseDirectory.IndexOf("\\bin")) + "\\wwwroot\\images\\users\\" + User.ImageFile.FileName;
                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            User.ImageFile.CopyToAsync(stream);
                        }
                    }

                    User.Picture = User.ImageFile.FileName;
                    //create
                    _db.Users.Add(User);
                }
                else
                {
                    _db.Users.Update(User);
                }
                _db.SaveChanges();
                
               

                return View("Reg_Success", User);
            }
            return View(User);
        }
    }
}

RecipeWebsite/RecipeWebsite/Views/Login/Index.cshtml
@using Microsoft.AspNetCore.Http;
@using Microsoft.AspNetCore.Identity
@using RecipeWebsite.Models
@model User

@inject IHttpContextAccessor HttpContextAccessor

@{
    ViewData["Title"] = "Login";
}
    <br />
    <div id="loginContainer" class="container">
        <div class="row  justify-content-center">
            <div class="col-6">
                <div><h4>Sign in with email</h4> </div>
            </div>
        </div><br>

        <!-- Form for login-->
        <form id="loginForm" class="mt-3 needs-validation" method="post">

            <!-- UserName input -->
            <div class="form-group row align-items-sm-center">
                <label class="d-none d-sm-block col-sm-3 col-form-label"
                       for="email">Email</label>
                <div class="col-12 col-sm-9">
                    <input type="text" class="form-control" name="email" id="email" placeholder="prerry@gmail.com" required value="shuixiutan@gmail.com" />
                </div>
            </div>
            <!-- End of UserName input -->
            <!-- password input -->
            <div class="form-group row align-items-sm-center">
                <label class="d-none d-sm-block col-sm-3 col-form-label"
                       for="password">Password</label>
                <div class="col-12 col-sm-9">
                    <input type="password" class="form-control" name="password" id="password" placeholder="Your Password" value="123456ab" required />
                </div>
            </div>
            <!-- End of password input -->
            <!-- Submit button -->
            <div class="row ">
                <div class="col-3 offset-3">
                    <button type="submit" class="btn btn-secondary form-control">Sign In</button>
                    <div class="col-12 col-sm-9">
                        <a asp-area="" asp-controller="Register" asp-action="Index">New user? Join here!</a>
                    </div>
                </div>
            </div>
        </form>

        @{
            if (Model.ExternalLogins.Count == 0)
            {
                <div>No external logins configured</div>
            }
            else
            {
                <form method="post" asp-action="ExternalLogin" asp-route-returnUrl="@Model.ReturnUrl">
                    <div>
                        @foreach (var provider in Model.ExternalLogins)
                        {
                            <button type="submit" class="btn btn-primary"
                                    name="provider" value="@provider.Name"
                                    title="Log in using your @provider.DisplayName account">
                                @provider.DisplayName
                            </button>
                        }
                    </div>
                </form>
            }
        }

    </div>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

RecipeWebsite/RecipeWebsite/Views/Login/Login_Success.cshtml
@model RecipeWebsite.Models.User
@{
    ViewData["Title"] = "Login Successfully.";
}
<h1>Hi @Model.Email</h1>
<h2>Login Successful.</h2>
<h3><a href="/">Home</a></h3>