RecipeWebsite/RecipeWebsite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using RecipeWebsite.Models;

namespace RecipeWebsite.Controllers
{
    public class HomeController : Controller
    {

        private readonly RecipeWebsiteDbContext _context;

        public HomeController(RecipeWebsiteDbContext context)
        {
            _context = context;
        }


        // GET: Recipes
        public async Task<IActionResult> Index()
        {
            var recipeWebsiteDbContext = _context.Recipes.Include(r => r.Category).Include(r => r.User);
            return View(await recipeWebsiteDbContext.ToListAsync());
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        #region API Calls
        [HttpPost]
        public async Task<IActionResult> SetFavorite(int recipeId)
        {
            if (recipeId == null)
            {
                return Json(new { success = false, message = " Invalid data!" });
            }
            int currentUserId = (int)HttpContext.Session.GetInt32("UserId");

            Userfavoriterecipe favorite = new Userfavoriterecipe();
            favorite.UserId = currentUserId;
            favorite.RecipeId = recipeId;
            _context.Userfavoriterecipes.Add(favorite);
            _context.SaveChanges();

            return Json(new { success = true, message = "Successfully collect to favorite!" });
        }
        #endregion
    }
}

RecipeWebsite/RecipeWebsite/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RecipeWebsite.Models;

namespace RecipeWebsite.Controllers
{
    public class ProfileController : Controller
    {
        private readonly RecipeWebsiteDbContext _db;
        [BindProperty]
        public User User { get; set; }
        public ProfileController(RecipeWebsiteDbContext db)
        {
            _db = db;
        }
        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
        }

        public IActionResult About()
        {
            HttpContext.Session.SetString("CurrentPage", "About");
            string email = HttpContext.Session.GetString("Email");
            if (email == null || email == "")
            {
                return RedirectToAction("Index", "Login");
            }
            var user = _db.Users.FirstOrDefaultAsync(u => u.Email == email);
            return View(user.Result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> About(int id, [Bind("Id,Email,Password,Username,Picture,Descrption")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _db.Update(user);
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return Json(new { success = true, message = "Update Successful!" });
            }
            return View(user);
        }

        public IActionResult Index()
        {
            //int userId = (int)HttpContext.Session.GetInt32("UserId");
            HttpContext.Session.SetString("CurrentPage", "ProIndex");
            int userId = 1;
            if (userId == null)
            {
                return RedirectToAction("Index", "Login");
            }
            List<Userfavoriterecipe> favoriterecipes = _db.Userfavoriterecipes.Include(u => u.User).Include(r => r.Recipe).Where(u => u.UserId == userId).ToList();
            foreach (var favoriterecipe in favoriterecipes)
            {
                int recipeCreateBy = favoriterecipe.Recipe.UserId;
                favoriterecipe.Recipe.User = _db.Users.Find(recipeCreateBy);
                favoriterecipe.Recipe.User.Follows = _db.Follows.Where(c => c.FollowingId == recipeCreateBy).ToList();
                favoriterecipe.Recipe.User.Userfavoriterecipes = _db.Userfavoriterecipes.Where(c => c.UserId == recipeCreateBy).ToList();
                favoriterecipe.Recipe.User.Recipes = _db.Recipes.Where(c => c.UserId == recipeCreateBy).ToList();
                favoriterecipe.Recipe.Comments = _db.Comments.Where(c => c.RecipeId == favoriterecipe.RecipeId).ToList();
            }
            return View("Index", favoriterecipes);
        }

        public IActionResult Friends()
        {
            HttpContext.Session.SetString("CurrentPage", "Friends");
            //int userId = (int)HttpContext.Session.GetInt32("UserId");
            int userId = 1;
            if (userId == null)
            {
                return RedirectToAction("Index", "Login");
            }
            List<User> users = _db.Users.ToList();
            return View("Friends", users);
        }

        [Route("Profile/Friends/Following")]
        public IActionResult Following()
        {
            //int userId = (int)HttpContext.Session.GetInt32("UserId");
            int userId = 1;
            if (userId == null)
            {
                return RedirectToAction("Index", "Login");
            }
            List<Follow> follows = _db.Follows.Include(u => u.Following).Where(u => u.FollowerId == userId).ToList();
            return View("Following", follows);
        }

        [Route("Profile/Friends/Follower")]
        public IActionResult Follower()
        {
            //int userId = (int)HttpContext.Session.GetInt32("UserId");
            int userId = 1;
            if (userId == null)
            {
                return RedirectToAction("Index", "Login");
            }
            List<Follow> follows = _db.Follows.Include(u => u.Follower).Where(u => u.FollowingId == userId).ToList();
            return View("Follower", follows);
        }

        public IActionResult MyReviews()
        {
            HttpContext.Session.SetString("CurrentPage", "MyReviews");
            //int userId = (int)HttpContext.Session.GetInt32("UserId");
            int userId = 1;
            if (userId == null)
            {
                return RedirectToAction("Index", "Login");
            }
            List<Comment> comments = _db.Comments.Include(u => u.User).Include(r => r.Recipe).Where(u => u.UserId == userId).ToList();
            return View("MyReviews", comments);
        }
        public IActionResult PersonalRecipes()
        {
            HttpContext.Session.SetString("CurrentPage", "PersonalRecipes");
            //int userId = (int)HttpContext.Session.GetInt32("UserId");
            int userId = 1;
            if (userId == null)
            {
                return RedirectToAction("Index", "Login");
            }
            List<Recipe> personalRecipes = _db.Recipes.Include(u => u.User).Include(c => c.Category).Where(u => u.UserId == userId).ToList();
            return View("PersonalRecipes", personalRecipes);
        }

        public IActionResult PersonalRecipeAdd()
        {
            return View();
        }

        private bool UserExists(int id)
        {
            return _db.Users.Any(e => e.Id == id);
        }

        #region API Calls
        [HttpPost]
        public async Task<IActionResult> SetFollow(int followingId)
        {
            if (followingId == null)
            {
                return Json(new { success = false, message = " Invalid data!" });
            }
            int followerId = (int)HttpContext.Session.GetInt32("UserId");

            Follow follow = new Follow();
            follow.FollowerId = followerId;
            follow.FollowingId = followingId;
            _db.Follows.Add(follow);
            _db.SaveChanges();

            return Json(new { success = true, message = "Successfully set the Following!" });
        }

        public async Task<IActionResult> CancelFollowing(int id)
        {
            if (id == null)
            {
                return Json(new { success = false, message = " Invalid data!" });
            }
            var follow = await _db.Follows.FindAsync(id);
            _db.Follows.Remove(follow);
            _db.SaveChanges();
            return Json(new { success = true, message = "Successfully cancel the Following!" });
        }

        [HttpPost]
        public async Task<IActionResult> Rating(int recipeId, int ratingNum, string description)
        {
            if (recipeId == null)
            {
                return Json(new { success = false, message = " Invalid data!" });
            }

            Comment comment = new Comment();
            comment.UserId = (int)HttpContext.Session.GetInt32("UserId");
            comment.Rating = ratingNum;
            comment.Description = description;
            comment.RecipeId = recipeId;
            _db.Comments.Add(comment);
            _db.SaveChanges();

            return Json(new { success = true, message = "Successfully Comment!" });
        }
        #endregion
    }
}

RecipeWebsite/RecipeWebsite/Views/Home/Index.cshtml
@model IEnumerable<RecipeWebsite.Models.Recipe>
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"] = "Home";
    var email = HttpContextAccessor.HttpContext.Session.GetString("Email");
    var username = HttpContextAccessor.HttpContext.Session.GetString("Username");
}

<br />
<div class="container">

    <br />
    <div class="row">
        <div class="col">
            <a href="#"><img src="~/images/recipe1.jpg" class="category" /></a>
            <a href="#"><p>BBQ & Grilled Shrimp </p></a>
        </div>
        <div class="col">
            <a href="#">
                <img src="~/images/recipe2.jpg" class="category" />
            </a>
            <a href="#"><p>Quarantine Cooking </p></a>
        </div>
        <div class="col">
            <a href="#">
                <img src="~/images/recipe3.jpg" class="category" />
            </a>
            <a href="#"><p>Cake Recipes </p></a>
        </div>
        <div class="col">
            <a href="#">
                <img src="~/images/recipe4.jpg" class="category" />
            </a>
            <a href="#"><p>Cheesecake Recipes </p></a>
        </div>
        <div class="col">
            <a href="#">
                <img src="~/images/recipe5.jpg" class="category" />
            </a>
            <a href="#"><p>Bundt Cake Recipes </p></a>
        </div>
        <div class="col">
            <a href="#">
                <img src="~/images/recipe6.jpg" class="category" />
            </a>
            <a href="#"><p>Shrimp Recipes </p></a>
        </div>

    </div>
    <br />
    <div class="row">
        <h3>Latest Recipes</h3>
    </div>
    <hr class="my-4">

    <div class="row">
        @foreach (var item in Model)
        {
        <div class="col-lg-3  col-md-auto">
            <br />
            <img src="~/images/@item.Picture" style="width:100%" /><br /><br />
            <div>
                <b>@item.Name</b><br />
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
                <i class="fas fa-star"></i>
            </div>
            <a href="#">Create by:Shuixiu Tan</a> <br /><br />
            @if (email == "" || email == null)
            {
                <a asp-area="" asp-controller="Login" asp-action="Index" class="btn btn-sm btn-secondary">
                    <i class="fas fa-heart" style="color: red"> </i>Add
                </a>
                <!-- Button trigger modal -->
                <a asp-area="" asp-controller="Login" asp-action="Index" class="btn  btn-sm btn-secondary">
                    Rating
                </a>
            }
            else
            {
                <button class="btnFavorite btn btn-sm btn-secondary" data-id="@item.Id" >
                    <i class="fas fa-heart" style="color: red"> </i>Add
                </button>
                <!-- Button trigger modal -->
                <button type="button" data-toggle="modal" data-target="#exampleModal" class="btn btn-sm btn-secondary">
                    Rating
                </button>
                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Rating and comment</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Your rating
                                <div style="font-size:30px;">
                                    <a href="#"><i class="fas fa-star rating-star" id="star1"></i></a>
                                    <a href="#"><i class="fas fa-star rating-star" id="star2"></i></a>
                                    <a href="#"><i class="fas fa-star rating-star" id="star3"></i></a>
                                    <a href="#"><i class="fas fa-star rating-star" id="star4"></i></a>
                                    <a href="#"><i class="fas fa-star rating-star" id="star5"></i></a>
                                </div>
                                Your review (optional)<br />
                                <textarea cols="60" rows="8" id="description">
                                    </textarea>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                <button type="button" class="btn btn-primary btnSubmit" data-recipeid="@item.Id">Submit</button>
                            </div>
                        </div>
                    </div>
                </div>
                <br />
                <br />
            }
        </div>
        }
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            $(".btnFavorite").click(function () {
                var recipeId = $(this).data('id');
                var arguments = { recipeId: recipeId };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("SetFavorite", "Home")',
                    data: arguments,
                    success: function (data) {
                        if (data.success) {
                            alert("SetFavorite successful!");
                        }
                        else {
                            alert("SetFavorite fail!");
                        }
                    },
                    error: function (data) {
                        //toastr.error(data.message);
                    }
                });
            });

            //rating
            var ratingNum = 0;
            $("#star1").click(function () {
                var color1 = $('#star1').css("color");
                if (color1 == "rgb(212, 213, 214)") {
                    ratingNum = 1;
                    $(this).css('color', '#e86017');
                } else {
                    $("#star2").css('color', '#d4d5d6');
                    $("#star3").css('color', '#d4d5d6');
                    $("#star4").css('color', '#d4d5d6');
                    $("#star5").css('color', '#d4d5d6');
                }
            });

            $("#star2").click(function () {
                var color2 = $('#star2').css("color");
                if (color2 == "rgb(212, 213, 214)") {
                    ratingNum = 2;
                    $("#star1").css('color', '#e86017');
                    $(this).css('color', '#e86017');
                } else {
                    $("#star3").css('color', '#d4d5d6');
                    $("#star4").css('color', '#d4d5d6');
                    $("#star5").css('color', '#d4d5d6');
                }
            });

            $("#star3").click(function () {
                var color3 = $('#star3').css("color");
                if (color3 == "rgb(212, 213, 214)") {
                    ratingNum = 3;
                    $("#star1").css('color', '#e86017');
                    $("#star2").css('color', '#e86017');
                    $(this).css('color', '#e86017');
                } else {
                    $("#star4").css('color', '#d4d5d6');
                    $("#star5").css('color', '#d4d5d6');
                }
            });

            $("#star4").click(function () {
                var color4 = $('#star4').css("color");
                if (color4 == "rgb(212, 213, 214)") {
                    ratingNum = 4;
                    $("#star1").css('color', '#e86017');
                    $("#star2").css('color', '#e86017');
                    $("#star3").css('color', '#e86017');
                    $(this).css('color', '#e86017');
                }
                else {
                    $("#star5").css('color', '#d4d5d6');
                }
            });

            $("#star5").click(function () {
                ratingNum = 5;
                $("#star1").css('color', '#e86017');
                $("#star2").css('color', '#e86017');
                $("#star3").css('color', '#e86017');
                $("#star4").css('color', '#e86017');
                $(this).css('color', '#e86017');
            });

            $(".btnSubmit").click(function () {
                var recipeid = $(this).data('recipeid');
                var description = $("#description").val();
                var arguments = { recipeid: recipeid, ratingNum: ratingNum,description: description };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Rating", "Profile")',
                    data: arguments,
                    success: function (data) {
                        if (data.success) {
                            alert("Rating successful!");
                            location.reload();
                        }
                        else {
                            alert("Rating fail!");
                        }
                    },
                    error: function (data) {
                        //toastr.error(data.message);
                    }
                });
            });

        });
    </script>
}

RecipeWebsite/RecipeWebsite/Views/Home/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RecipeWebsite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- Font Awesome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0-1/css/all.min.css" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/logo.JPG"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                &nbsp;&nbsp;&nbsp;
                <form class="form-inline my-4 my-lg-0" style="margin-left:30px;">
                    <input class="form-control col-xl-auto mr-sm-4" type="search" placeholder="Find a recipe" aria-label="Search">
                    <button type="submit" class="btn btn-danger"> <i class="fas fa-search"></i> </button>
                </form>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav><br/>
    </header>
    <img src="~/images/wide_32.jpg" style="width:100%;margin-top:-50px;">
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <br /><br /><br />
    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2020 - RecipeWebsite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>