RecipeWebsite/RecipeWebsite/Models/Recipe.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace RecipeWebsite.Models
{
    public class Recipe
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public string Ingredients { get; set; }

        [Required]
        public string Directions { get; set; }

        [Required]
        public string Picture { get; set; }

        [NotMapped]
        public IFormFile ImageFile { get; set; }

        [Required]
        public int UserId { get; set; }
        public virtual User User { get; set; }

        [Required]
        public int CategoryId { get; set; }
        public virtual Category Category { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Userfavoriterecipe> Userfavoriterecipes { get; set; }
    }
}

RecipeWebsite/RecipeWebsite/Controllers/RecipesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RecipeWebsite.Models;

namespace RecipeWebsite.Controllers
{
    public class RecipesController : Controller
    {
        private readonly RecipeWebsiteDbContext _context;

        public RecipesController(RecipeWebsiteDbContext context)
        {
            _context = context;
        }

        public Recipe Recipe { get; set; }
        // GET: Recipes
        public async Task<IActionResult> Index()
        {
            var recipeWebsiteDbContext = _context.Recipes.Include(r => r.Category).Include(r => r.User);
            return View(await recipeWebsiteDbContext.ToListAsync());
        }

        // GET: Recipes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recipe = await _context.Recipes
                .Include(r => r.Category)
                .Include(r => r.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (recipe == null)
            {
                return NotFound();
            }

            return View(recipe);
        }

        // GET: Recipes/Create
        public IActionResult Create()
        {
            //ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Code");
            //ViewData["UserId"] = new SelectList(_context.Users, "Id", "Email");
            List<Category> categories = _context.Categories.ToList();
            ViewBag.Categories = categories;
            return View();
        }

        // POST: Recipes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Ingredients,Directions,Picture,UserId,CategoryId,ImageFile")] Recipe recipe)
        {
            if (true || ModelState.IsValid)
            {
                if (recipe.ImageFile.Length > 0)
                {
                    string filePath = AppDomain.CurrentDomain.BaseDirectory.Substring(0, AppDomain.CurrentDomain.BaseDirectory.IndexOf("\\bin")) + "\\wwwroot\\images\\recipes\\" + recipe.ImageFile.FileName;
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await recipe.ImageFile.CopyToAsync(stream);
                    }
                }

                recipe.Picture = recipe.ImageFile.FileName;
                //create
                recipe.UserId = (int)HttpContext.Session.GetInt32("UserId");
                _context.Add(recipe);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            List<Category> categories = _context.Categories.ToList();
            ViewBag.Categories = categories;
            return View(Recipe);
        }

        // GET: Recipes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recipe = await _context.Recipes.FindAsync(id);
            if (recipe == null)
            {
                return NotFound();
            }
            //ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Code", recipe.CategoryId);
            //ViewData["UserId"] = new SelectList(_context.Users, "Id", "Email", recipe.UserId);
            List<Category> categories = _context.Categories.ToList();
            ViewBag.Categories = categories;
            return View(recipe);
        }

        // POST: Recipes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Ingredients,Directions,Picture,UserId,CategoryId")] Recipe recipe)
        {
            if (id != recipe.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(recipe);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RecipeExists(recipe.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Code", recipe.CategoryId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Email", recipe.UserId);
            return View(recipe);
        }

        // GET: Recipes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var recipe = await _context.Recipes
                .Include(r => r.Category)
                .Include(r => r.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (recipe == null)
            {
                return NotFound();
            }

            return View(recipe);
        }

        // POST: Recipes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var recipe = await _context.Recipes.FindAsync(id);
            _context.Recipes.Remove(recipe);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RecipeExists(int id)
        {
            return _context.Recipes.Any(e => e.Id == id);
        }
    }
}

RecipeWebsite/RecipeWebsite/Views/Recipes/Create.cshtml
@model RecipeWebsite.Models.Recipe
@{
    ViewData["Title"] = "Create";
    Layout = "_Layout";
    var categories = ViewBag.Categories;
}

<div class="container about-main">
    <h1 class="pb-3">Create recipe</h1>
    <div class="row">
        <div class="col">
            <form method="post"  enctype="multipart/form-data">
                <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-6">
                        <input asp-for="Name" name="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="CategoryId"></label>
                    </div>
                    <div class="col-6">
                        <select name="CategoryId">
                            @foreach (var category in categories)
                            {
                                <option value="@category.Id">@category.Code</option>
                            }
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Description"></label>
                    </div>
                    <div class="col-6">
                        <input asp-for="Description" name="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Ingredients"></label>
                    </div>
                    <div class="col-6">
                        <textarea rows="15" cols="100" asp-for="Ingredients" name="Ingredients" class="form-control"></textarea>
                        <span asp-validation-for="Ingredients" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Directions"></label>
                    </div>
                    <div class="col-6">
                        <textarea rows="15" cols="100" asp-for="Directions" name="Directions" class="form-control"></textarea>
                        <span asp-validation-for="Directions" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Picture"></label>
                    </div>
                    <div class="col-6">
                        <input id="ImagePath" asp-for="Picture" title="Upload a product image"
                               type="file" name="ImageFile" /><br />
                        <span asp-validation-for="Picture" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-3 offset-3">
                        <button type="submit" class="btn btn-secondary form-control">Add Recipe</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div>
    <a asp-action="Index">Return to main page</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RecipeWebsite/RecipeWebsite/Views/Recipes/Delete.cshtml
@model RecipeWebsite.Models.Recipe

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Recipe</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ingredients)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ingredients)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Directions)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Directions)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Picture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Picture)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Email)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Code)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RecipeWebsite/RecipeWebsite/Views/Recipes/Details.cshtml
@model RecipeWebsite.Models.Recipe

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Recipe</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ingredients)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ingredients)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Directions)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Directions)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Picture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Picture)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Code)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

RecipeWebsite/RecipeWebsite/Views/Recipes/Edit.cshtml
@model RecipeWebsite.Models.Recipe

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Recipe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ingredients" class="control-label"></label>
                <input asp-for="Ingredients" class="form-control" />
                <span asp-validation-for="Ingredients" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Directions" class="control-label"></label>
                <input asp-for="Directions" class="form-control" />
                <span asp-validation-for="Directions" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Picture" class="control-label"></label>
                <input asp-for="Picture" class="form-control" />
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RecipeWebsite/RecipeWebsite/Views/Recipes/Index.cshtml
@model IEnumerable<RecipeWebsite.Models.Recipe>

@{
    ViewData["Title"] = "Home";
}

<div class="container">
    <div class="row">
        <p></p>
    </div>
    <div class="jumbotron">
        <h1>Welcome to Quick Recipes</h1>
        <hr class="my-4">
        <div class="row">
            <div class="col-3">
                <p>
                    <a class="btn btn-outline-secondary btn-lg" asp-controller="Recipes" asp-action="Create" role="button">Create a recipe</a>
                </p>
            </div>
            <div class="col-6">
            </div>
        </div>
        <p class="lead pt-2">or search using keywords:</p>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Sugar cookies" aria-label="Search">
            <button type="submit" class="btn btn-danger"> <i class="fas fa-search"></i> </button>
        </form>

    </div>
    <div class="row">
        <h3>Latest Recipes</h3>
    </div>
    <hr class="my-4">
    <div class="row">
        <p></p>
    </div>
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-3  col-md-auto">
                <img src="~/images/@item.Picture" style="width:100%" /><br /><br />
                <div>
                    <b>@item.Name</b><br />
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                </div>
            </div>
        }
    </div>
</div>